#!/bin/sh

print_help () {
	echo "Usage:"
	echo "	$0  to_synaptics-usb | to_usbhid"
	echo
	echo "to_synaptics-usb :  rebind devices to driver synaptics-usb"
	echo "to_usbhid        :  rebind devices to driver usbhid (kernel >= 2.6.13)"
	echo
	exit 1
}

if [ $# -ne 1 ] ; then
	print_help
fi

case $1 in
	to_usbhid) 		/usr/local/sbin/synaptics-usb rebind_to usbhid ;;
	to_synaptics-usb)	/usr/local/sbin/synaptics-usb rebind_to synaptics-usb ;;
	*)			print_help ;;
esac

exit
