#!/bin/bash

KSRC=$1
KVER=$2
DVER=$3
VCODE=`./version_code`
BDIR=`pwd`

leave ()
{
	cd $BDIR
	rm -rf tmp
	exit $1
}

if [ $VCODE -ge 132623 ] ; then
	BASE_PATCH=2.6.15-base.patch
else
	BASE_PATCH=2.6.0-base.patch
fi

rm -rf tmp
mkdir tmp
cd tmp

mkdir linux-$KVER
cd linux-$KVER
mkdir drivers
mkdir drivers/usb
mkdir drivers/usb/input
cp $KSRC/drivers/usb/input/Makefile drivers/usb/input
cp $KSRC/drivers/usb/input/Kconfig drivers/usb/input
cd ..

cp -r linux-$KVER linux-$KVER-synusb
cd linux-$KVER-synusb
patch -p1 --no-backup-if-mismatch -i ../../$BASE_PATCH || leave 1
mkdir include
mkdir include/linux
cp ../../../synaptics-usb.c drivers/usb/input
cp ../../../cpad.h include/linux
#echo Press return to continue...; read
if [ $VCODE -le 132626 ] ; then
	cp ../../../synusb-kcompat.h drivers/usb/input
else
	patch -p1 --no-backup-if-mismatch -i ../../cleanup.patch || leave 1
fi
cd ..

diff -ruN linux-$KVER linux-$KVER-synusb > ../../kernel-patches/synaptics-usb-$DVER-for-$KVER.patch

leave 0
