#!/bin/bash

KSRC=$1
KVER=$2
DVER=$3
VCODE=`./version_code`
BDIR=`pwd`

leave ()
{
	cd $BDIR
	rm -rf tmp
	exit $1
}

if [ $VCODE -ge 132639 ] ; then
	BASE_PATCH=2.6.31-base.patch
elif [ $VCODE -ge 132638 ] ; then
	BASE_PATCH=2.6.30-base.patch
elif [ $VCODE -ge 132637 ] ; then
	BASE_PATCH=2.6.29-base.patch
else
	BASE_PATCH=base.patch
fi

rm -rf tmp
mkdir tmp
cd tmp

mkdir linux-$KVER
cd linux-$KVER
mkdir drivers
mkdir drivers/input
mkdir drivers/input/mouse
cp $KSRC/drivers/input/mouse/Makefile drivers/input/mouse
cp $KSRC/drivers/input/mouse/Kconfig drivers/input/mouse
cd ..

cp -r linux-$KVER linux-$KVER-synusb
cd linux-$KVER-synusb
#echo Press return to continue...; read
patch -p1 --no-backup-if-mismatch -i ../../$BASE_PATCH || leave 1
mkdir include
mkdir include/linux
cp ../../../synapticsusb.c drivers/input/mouse
cp ../../../synapticsusb.h drivers/input/mouse
cp ../../../cpad.c drivers/input/mouse
cp ../../../cpad.h drivers/input/mouse
cp ../../../linux/cpad.h include/linux
#echo Press return to continue...; read
if [ $VCODE -le 132631 ] ; then
	cp ../../../synusb-kcompat.h drivers/input/mouse
else
	patch -p1 --no-backup-if-mismatch -i ../../cleanup.patch || leave 1
fi
cd ..

diff -ruN linux-$KVER linux-$KVER-synusb > ../../kernel-patches/synaptics-usb-$DVER-for-$KVER.patch

leave 0
